kind: Service
apiVersion: v1
metadata:
  name: redis-prom
  namespace: redis-ns
  annotations:
    prometheus.io/scrape: 'true' # 让上面的自动发现能获取该服务
    prometheus.io/port: '9121' # 指定metrics接口访问端口
    rometheus.io/path: "/metrics"    # 指定指标路径
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
    - name: prom
      port: 9121
      targetPort: 9121