apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-mon
data:
  prometheus.yaml.tmpl: |
    # 全局配置
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
      external_labels:
        cluster: shixiaochuang-test
        replica: $(POD_NAME)  # 每个 Prometheus 有一个唯一的标签

    # Alertmanager（如暂不使用可保持为空）
    alerting:
      alert_relabel_configs:
        # 我们希望告警从不同的副本中也是去重的
        - regex: replica
          action: labeldrop
      alertmanagers:
        - static_configs:
            - targets: [""]
    
    # 告警规则文件
    rule_files:
      - "/etc/prometheus/rules/*.yml"

    scrape_configs:
      # 1. 监控 Prometheus 自身
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      # 2. 采集 kube-state-metrics 指标
      - job_name: "kube-state-metrics"
        scrape_interval: 30s
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - ksm-ns
        relabel_configs:
          # 仅保留 kube-state-metrics Service
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: kube-state-metrics
          # 仅保留 http-metrics 端口
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http-metrics
          # 映射 Service Labels
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          # 命名空间标签
          - source_labels: [__meta_kubernetes_namespace]
            target_label: k8s_namespace
          # Service 名称标签
          - source_labels: [__meta_kubernetes_service_name]
            target_label: k8s_sname
          # Pod 名称作为 instance
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: instance