apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutemiddle
  namespace: traefik-ns

spec:
  entryPoints:
    - web
  routes:
  - match: Host(`ipwhitelist.shixiaochuang.org`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: service-middle
      port: 80
      namespace: traefik-ns
    middlewares:
    - name: gs-ipwhitelist