kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-web-middleware
  namespace: traefik-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middle
  template:
    metadata:
      labels:
        app: middle
    spec:
      containers:
        - name: nginx-web-c
          image: shixiaochuangk8s/nginx:1.15-alpine
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: service-middle
  namespace: traefik-ns

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: middle