apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: traefik-ns

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: v1
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
  namespace: traefik-ns

spec:
  ports:
    - name: http
      port: 80
  selector:
    app: v2