apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongo-traefik-tcp
  namespace: traefik-ns
spec:
  entryPoints:
    - mongo
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mongo-traefik
          port: 27017