apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-traefik
  namespace: traefik-ns
  labels:
    app: mongo-traefik
spec:
  selector:
    matchLabels:
      app: mongo-traefik
  template:
    metadata:
      labels:
        app: mongo-traefik
    spec:
      containers:
        - name: mongo
          image: shixiaochuangk8s/mongo:8.0.16
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-traefik
  namespace: traefik-ns
spec:
  selector:
    app: mongo-traefik
  ports:
    - port: 27017