apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: myingressroute
  namespace: traefik-ns
spec:
  entryPoints:
    - web

  routes:
  - match: Host(`nginx.shixiaochuang.org`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: service-nginx-app
      port: 80