apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-https
  namespace: traefik-ns
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`nginx.shixiaochuang.org`)
    kind: Rule
    services:
      - name: service-nginx-app
        port: 80
  tls:
    secretName: nginx-tls-secret