apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressrouteudpwho
  namespace: traefik-ns
spec:
  entryPoints:
    - udpep
  routes:
  - services:
    - name: whoamiudp
      port: 8080
