apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: alertmanager-ns
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alert.shixiaochuang.org`)
      kind: Rule
      services:
        - name: alertmanager
          port: 9093