apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: alertmanager-ns
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:587'
      smtp_from: 'shixiaochuangwork@foxmail.com'
      smtp_auth_username: 'shixiaochuangwork@foxmail.com'
      smtp_auth_password: 'uystnxszuxeccfhi'
      smtp_hello: 'qq.com'
      smtp_require_tls: true

    templates:
      - '/etc/alertmanager/template/*.tmpl'

    route:
      group_by: ['alertname', 'cluster']
      group_wait: 1m
      group_interval: 3m
      repeat_interval: 10m
      receiver: 'default-receiver'  # 默认接收者

      # 子路由：按告警名称前缀分发
      routes:
        - matchers:
            - alertname =~ "Deployment.*"
          receiver: 'email'

        - matchers:
            - alertname =~ "PersistentVolume.*"
          receiver: 'wechat'

    receivers:
      - name: 'default-receiver'
        wechat_configs:
          - send_resolved: true
            api_url: https://qyapi.weixin.qq.com/cgi-bin/
            corp_id: ww38c6ff6961b90a38
            to_user: ShiXiaoChuang
            agent_id: "1000002"
            api_secret: T_5mDY9JJPfMDiYVpJj-qJJCM14q8vk6b8zUF0d-EWk
            message: '{{ template "wechat.default.message" . }}'

      - name: 'email'
        email_configs:
          - to: 'wadeshamer30@gmail.com'
            send_resolved: true
            headers:
              Subject: '[K8s告警] Deployment异常'
            html: '{{ template "email.default.html" . }}'

      - name: 'wechat'
        wechat_configs:
          - send_resolved: true
            api_url: https://qyapi.weixin.qq.com/cgi-bin/
            corp_id: ww38c6ff6961b90a38
            to_user: ShiXiaoChuang
            agent_id: "1000002"
            api_secret: T_5mDY9JJPfMDiYVpJj-qJJCM14q8vk6b8zUF0d-EWk
            message: '{{ template "wechat.default.message" . }}'