apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kube-mon
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "name": "thanos-querier",
          "type": "prometheus",
          "access": "proxy",
          "url": "http://thanos-querier.kube-mon.svc.cluster.local:9090",
          "orgId": 1,
          "editable": true,
          "version": 1
        }
      ]
    }