apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: kube-mon
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:587'
      smtp_from: 'shixiaochuangwork@foxmail.com'
      smtp_auth_username: 'shixiaochuangwork@foxmail.com'
      smtp_auth_password: 'uystnxszuxeccfhi'
      smtp_hello: 'qq.com'
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'cluster']
      group_wait: 1m
      group_interval: 3m
      repeat_interval: 10m
      receiver: 'email'

    receivers:
      - name: 'email'
        email_configs:
          - to: 'shixiaochuangbeta@gmail.com'
            send_resolved: true