apiVersion: apps/v1
kind: Deployment
metadata:
  name: pc-deployment-rollingupdate
  namespace: pod-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rollingupdate
  strategy:
    type: RollingUpdate                # 使用滚动更新策略
    rollingUpdate:
      maxSurge: 25%                    # 更新时最多允许额外创建 25% Pod
      maxUnavailable: 25%              # 更新时最多允许 25% Pod 不可用
  template:
    metadata:
      labels:
        app: nginx-rollingupdate
    spec:
      containers:
        - name: nginx
          image: shixiaochuangk8s/nginx:1.17.1