apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmselect
  namespace: kube-vm
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: 'nginx'
  rules:
    - host: vmcluster.shixiaochuang.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmselect
                port:
                  number: 8481