apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana-ns
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "name": "victoria-metrics",
          "type": "prometheus",
          "access": "proxy",
          "url": "http://victoria-metrics.kube-vm-single.svc.cluster.local:8428",
          "orgId": 1,
          "editable": true,
          "version": 1,
          "isDefault": true
        }
      ]
    }