apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus-ns
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    remote_write:
      - url: "http://vminsert.kube-vm.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
        queue_config:
          max_samples_per_send: 10000
          max_shards: 10
          capacity: 20000

    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    rule_files: []

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
            labels:
              app: "prometheus"

      - job_name: "nodes"
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__address__]
            regex: '(.*):10250'
            replacement: '${1}:9100'
            target_label: __address__
            action: replace

      - job_name: "vmselect"
        static_configs:
          - targets:
              - vmselect.kube-vm.svc.cluster.local:8481
            labels:
              component: "vmselect"

      - job_name: "vminsert"
        static_configs:
          - targets:
              - vminsert.kube-vm.svc.cluster.local:8480
            labels:
              component: "vminsert"

      - job_name: "vmstorage"
        static_configs:
          - targets:
              - vmstorage-0.cluster-vmstorage.kube-vm.svc.cluster.local:8482
              - vmstorage-1.cluster-vmstorage.kube-vm.svc.cluster.local:8482
              - vmstorage-2.cluster-vmstorage.kube-vm.svc.cluster.local:8482
            labels:
              component: "vmstorage"