apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: kube-vm-single
spec:
  type: ClusterIP
  selector:
    app: victoria-metrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      protocol: TCP